name: antigen
channels:
  - conda-forge
  - bioconda
dependencies:
  - pyyaml
  - python=3.10
  - pip
  - numpy
  - pandas
  - ipython
  - ipykernel
  - matplotlib
  - seaborn
  - scikit-learn
  - biopython
  - pytest
  - augur
  - auspice
  - importlib_resources
  - r-base
  - r-irkernel
  - rpy2
  - libxml2
  - r-igraph
  - r-essentials
  - r-ape
  - r-phytools
  - r-stringr
  - r-metbrewer
  - r-mgcv
  - r-cowplot
  - r-ggplot2
  - r-binom
  - r-cmdstanr
  - pip:
    - pathogen-embed
    - evofr
    - baltic
