name: antigen
channels:
  - conda-forge
  - bioconda
dependencies:
  - pyyaml
  - python=3.10
  - pip
  - numpy
  - pandas
  - ipython
  - ipykernel
  - matplotlib
  - seaborn
  - scikit-learn
  - biopython
  - pytest
  - augur
  - auspice
  - importlib_resources
  - pip:
    - pathogen-embed
